-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Crop_Seeding"
(
    "Crop_Name" text COLLATE pg_catalog."default",
    "Seeding_Day" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Weather_Report"
(
    "Reported_Weather_Type" text COLLATE pg_catalog."default",
    "Reporting_Time" timestamp without time zone,
    id numeric
);

CREATE TABLE IF NOT EXISTS public."Weather_Info"
(
    "Day" text COLLATE pg_catalog."default",
    "Weather_Type" text COLLATE pg_catalog."default"
);
END;